### ISSUE TITLE
When releasing a version CI on GitHub fails when closing the milestone

### ISSUE THREAD

**Issue by nils-a** [cake-contrib/Cake.Coveralls#150]
## Expected Behavior

After pushing a release the milestone should be closed.

## Current Behavior

The milestone is not closed. The error is:

```text
Executing: "D:/a/Cake.Coveralls/Cake.Coveralls/tools/dotnet-gitreleasemanager.exe" close --token "[REDACTED]" -o "***" -r "Cake.Coveralls" -m "2.0.0"

   ____ _ _   ____      _                     __  __
  / ___(_) |_|  _ \ ___| | ___  __ _ ___  ___|  \/  | __ _ _ __   __ _  __ _  ___ _ __
 | |  _| | __| |_) / _ \ |/ _ \/ _` / __|/ _ \ |\/| |/ _` | '_ \ / _` |/ _` |/ _ \ '__|
 | |_| | | |_|  _ <  __/ |  __/ (_| \__ \  __/ |  | | (_| | | | | (_| | (_| |  __/ |
  \____|_|\__|_| \_\___|_|\___|\__,_|___/\___|_|  |_|\__,_|_| |_|\__,_|\__, |\___|_|
                                                                       |___/
                                                                                 0.17.0

Using GitHub as VCS Provider
Closing milestone 2.0.0
Adding release comment for Issue #147
[FTL] Value was either too large or too small for an Int32.
GitReleaseManager.Core.Exceptions.ApiException: Value was either too large or too small for an Int32.
 ---> System.OverflowException: Value was either too large or too small for an Int32.
   at System.Convert.ThrowInt32OverflowException()
   at System.Convert.ToInt32(Int64 value)
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at Octokit.PocoJsonSerializerStrategy.DeserializeObject(Object value, Type type) in /_/Octokit/SimpleJson.cs:line 1528
   at Octokit.Internal.SimpleJsonSerializer.GitHubSerializerStrategy.DeserializeObject(Object value, Type type) in /_/Octokit/Http/SimpleJsonSerializer.cs:line 183
   at Octokit.PocoJsonSerializerStrategy.DeserializeObject(Object value, Type type) in /_/Octokit/SimpleJson.cs:line 1528
   at Octokit.Internal.SimpleJsonSerializer.GitHubSerializerStrategy.DeserializeObject(Object value, Type type) in /_/Octokit/Http/SimpleJsonSerializer.cs:line 183
   at Octokit.SimpleJson.DeserializeObject(String json, Type type, IJsonSerializerStrategy jsonSerializerStrategy) in /_/Octokit/SimpleJson.cs:line 584
   at Octokit.SimpleJson.DeserializeObject[T](String json, IJsonSerializerStrategy jsonSerializerStrategy) in /_/Octokit/SimpleJson.cs:line 596
   at Octokit.Internal.SimpleJsonSerializer.Deserialize[T](String json) in /_/Octokit/Http/SimpleJsonSerializer.cs:line 22
   at Octokit.Internal.JsonHttpPipeline.DeserializeResponse[T](IResponse response) in /_/Octokit/Http/JsonHttpPipeline.cs:line 62
   at Octokit.Connection.Run[T](IRequest request, CancellationToken cancellationToken, Func`2 preprocessResponseBody) in /_/Octokit/Http/Connection.cs:line 752
   at Octokit.ApiConnection.Post[T](Uri uri, Object data, String accepts, String contentType, CancellationToken cancellationToken) in /_/Octokit/Http/ApiConnection.cs:line 331
   at GitReleaseManager.Core.Provider.GitHubProvider.<>c__DisplayClass9_0.<<CreateIssueCommentAsync>b__0>d.MoveNext() in /_/src/GitReleaseManager.Core/Provider/GitHubProvider.cs:line 92
--- End of stack trace from previous location ---
   at GitReleaseManager.Core.Provider.GitHubProvider.ExecuteAsync(Func`1 action) in /_/src/GitReleaseManager.Core/Provider/GitHubProvider.cs:line 363
   --- End of inner exception stack trace ---
   at GitReleaseManager.Core.Provider.GitHubProvider.ExecuteAsync(Func`1 action) in /_/src/GitReleaseManager.Core/Provider/GitHubProvider.cs:line 375
   at GitReleaseManager.Core.VcsService.AddIssueCommentsAsync(String owner, String repository, Milestone milestone) in /_/src/GitReleaseManager.Core/VcsService.cs:line 399
   at GitReleaseManager.Core.VcsService.CloseMilestoneAsync(String owner, String repository, String milestoneTitle) in /_/src/GitReleaseManager.Core/VcsService.cs:line 262
   at GitReleaseManager.Core.Commands.CloseCommand.ExecuteAsync(CloseSubOptions options) in /_/src/GitReleaseManager.Core/Commands/CloseCommand.cs:line 21
   at GitReleaseManager.Cli.Program.Main(String[] args) in /_/src/GitReleaseManager.Cli/Program.cs:line 36
An error occurred when executing task 'Publish-GitHub-Release'.
GitReleaseManager: Process returned an error (exit code 1).
Publish-GitHub-Release Task failed, but continuing with next Task...
```

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Addin version used:
* Cake Version used:
* Operating System:

**Comment by nils-a** [comment]
Not sure, where the error came from, but everything worked perfect.

**Comment by nils-a** [comment]
Resurrecting this, as the error is still present.

**Comment by nils-a** [comment]
GitReleaseManager [v0.18.0](https://github.com/GitTools/GitReleaseManager/releases/tag/0.18.0) uses Octokit [v12.0.0](https://github.com/octokit/octokit.net/releases/tag/v12.0.0) where this is fixed.

So, bumping GRM to 0.18.0 will fix this.

**Comment by gep13** [comment]
Closing comment for posterity — the underlying fix landed in [#196](https://github.com/cake-contrib/Cake.Coveralls/pull/196) (removing the `recipe.cake` override that was pinning GRM to 0.17.0, so Cake.Recipe 4.0.0's bundled default 0.20.0 with a newer Octokit takes effect).

Validated end-to-end by the v6.0.0 tag-push run ([25481685558](https://github.com/cake-contrib/Cake.Coveralls/actions/runs/25481685558)): `Publish-GitHub-Release` ran through `CloseMilestoneAsync` + `AddIssueCommentsAsync` without incident, milestone 6.0.0 closed cleanly with all auto-comments posted. The same flow had crashed mid-publish on v5.0.0 with the exact `[FTL] Value was either too large or too small for an Int32` stack trace originally reported here.
