### ISSUE TITLE
Cake.Coveralls 0.6.0 can't be used with Cake (0.22.0)

### ISSUE THREAD

**Issue by Lakritzator** [cake-contrib/Cake.Coveralls#26]
When using Cake.Coveralls the following error comes:

```
Cake.exe : Error: The assembly 'Cake.Coveralls, Version=0.6.0.0, Culture=neutral, PublicKeyToken=null' 
At line:1 char:1
+ & "C:\projects\project\tools\Cake\Cake.exe" "build.cake" -targe ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Error: The asse...KeyToken=null' :String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
is referencing an older version of Cake.Core (0.21.1). 
This assembly need to reference at least Cake.Core version 0.22.0. 
Another option is to downgrade Cake to an earlier version. 
It's not recommended, but you can explicitly opt-out of assembly verification 
by configuring the Skip Verification setting to true
(i.e. command line parameter "--settings_skipverification=true", 
envrionment variable "CAKE_SETTINGS_SKIPVERIFICATION=true", 
read more about configuration at https://cakebuild.net/docs/fundamentals/configuration)
```

Cake recently introduced breaking-change for Cake see:
https://www.cakebuild.net/blog/2017/09/cake-v0.22.0-released

I would have expected that the 0.6 version already "covered" these?

P.S.
Running the script with skip verification is not an option, the following error comes:
```
An unknown exception has occurred.
Object reference not set to an instance of an object.
   at Coveralls.Net.CommandLineOptions.get_InputFiles() in C:\Users\jason\src\open-source\coveralls.net\coveralls.net\CommandLineOptions.cs:line 35
   at Coveralls.CoverallsBootstrap.get_CoverageFiles() in C:\Users\jason\src\open-source\coveralls.net\Coveralls.Lib\CoverallsBootstrap.cs:line 102
   at Coveralls.Net.Program.Run(CommandLineOptions options) in C:\Users\jason\src\open-source\coveralls.net\coveralls.net\Program.cs:line 40
   at Coveralls.Net.Program.Main(String[] args) in C:\Users\jason\src\open-source\coveralls.net\coveralls.net\Program.cs:line 18
Cake.exe : An error occurred when executing task 'UploadCoverageReport'.
At line:1 char:1
+ & "C:\projects\project\tools\Cake\Cake.exe" "build.cake" -targe ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (An error occurr...overageReport'.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
Error: 
One or more errors occurred.
Command executed with exception:
```

**Comment by Lakritzator** [comment]
It seems #27 would solve this.

**Comment by Lakritzator** [comment]
Thanks for updating!!

Unfortunately the error I got when I turned of validation was not due to the changes from you but seems to be an issue in Coveralls.net. So, cake is no longer complaining but the build still failed.

For those using Coveralls.io who are interested, I reported the issue here: coveralls-net/coveralls.net#36

**Comment by Lakritzator** [comment]
Some additional information: I changed from CoverallsIo to CoverallsNet (and changed the tool) and this worked.
